# Generated by Django 4.0.1 on 2022-01-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_todo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
