# Generated by Django 4.0.1 on 2022-01-23 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_todo_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='edited',
            new_name='is_edited',
        ),
    ]
